"""Added date of death column

Revision ID: 98001d1af32e
Revises: 
Create Date: 2021-02-24 21:53:44.350037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98001d1af32e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dod', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.drop_column('dod')

    # ### end Alembic commands ###
