"""Added age column

Revision ID: b7985bb473b9
Revises: 98001d1af32e
Create Date: 2021-02-26 20:47:17.045478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7985bb473b9'
down_revision = '98001d1af32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focuspeople')
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.drop_column('age')

    op.create_table('focuspeople',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('focus_father', sa.INTEGER(), nullable=True),
    sa.Column('focus_mother', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['focus_father'], ['individual.id'], ),
    sa.ForeignKeyConstraint(['focus_mother'], ['individual.id'], name='fk_focuspeople_focus_mother_individual'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
